# Generated by Django 5.1.3 on 2024-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id_email', models.CharField(db_column='id_email', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Specialize',
                'managed': False,
            },
        ),
    ]
