# Generated by Django 5.1.3 on 2024-11-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('disease_code', models.OneToOneField(db_column='disease_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='diseases.disease')),
                ('first_enc_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Discover',
                'managed': False,
            },
        ),
    ]
